### ISSUE TITLE
Support for Check In to any event

### ISSUE THREAD

**Issue by scottluskcis** [urbanengine/urban-engine-api#26]
Provide ability for users to check in for events including co working night, workshops, and the like

**Comment by scottluskcis** [comment]
@tylerbhughes please add any details

**Comment by tylerbhughes** [comment]
We might not need this right away as we have some issues with the current workflow which might need to be thought through again.

**Comment by PallasStreams** [comment]
Per discussion with the team, check in will eventually be moved to it's own application.
